// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: hello_world.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeteraaaClient is the client API for Greeteraaa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeteraaaClient interface {
	// 该服务包含一个 SayHello 方法 HelloRequest、HelloReply分别为该方法的输入与输出
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHello2(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeteraaaClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeteraaaClient(cc grpc.ClientConnInterface) GreeteraaaClient {
	return &greeteraaaClient{cc}
}

func (c *greeteraaaClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeteraaa/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeteraaaClient) SayHello2(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeteraaa/SayHello2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeteraaaServer is the server API for Greeteraaa service.
// All implementations must embed UnimplementedGreeteraaaServer
// for forward compatibility
type GreeteraaaServer interface {
	// 该服务包含一个 SayHello 方法 HelloRequest、HelloReply分别为该方法的输入与输出
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHello2(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGreeteraaaServer()
}

// UnimplementedGreeteraaaServer must be embedded to have forward compatible implementations.
type UnimplementedGreeteraaaServer struct {
}

func (UnimplementedGreeteraaaServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeteraaaServer) SayHello2(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello2 not implemented")
}
func (UnimplementedGreeteraaaServer) mustEmbedUnimplementedGreeteraaaServer() {}

// UnsafeGreeteraaaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeteraaaServer will
// result in compilation errors.
type UnsafeGreeteraaaServer interface {
	mustEmbedUnimplementedGreeteraaaServer()
}

func RegisterGreeteraaaServer(s grpc.ServiceRegistrar, srv GreeteraaaServer) {
	s.RegisterService(&Greeteraaa_ServiceDesc, srv)
}

func _Greeteraaa_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeteraaaServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeteraaa/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeteraaaServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeteraaa_SayHello2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeteraaaServer).SayHello2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeteraaa/SayHello2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeteraaaServer).SayHello2(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeteraaa_ServiceDesc is the grpc.ServiceDesc for Greeteraaa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeteraaa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeteraaa",
	HandlerType: (*GreeteraaaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeteraaa_SayHello_Handler,
		},
		{
			MethodName: "SayHello2",
			Handler:    _Greeteraaa_SayHello2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello_world.proto",
}
